### ISSUE TITLE
Update frontend development environment

### ISSUE THREAD

**Issue by norling** [NBISweden/theherdbook#243] opened 2021-04-20 10:35 UTC
The current frontend development environment is getting outdated and is quite hard to work with, which needs to be addressed.

- Currently the project is built using snowpack, 2.14, but the latest version is 3.3, so snowpack should be updated or replaced with another build tool.
- The current environment mixes the development and production pages invisibly (production is displayed if develop is unavailable). This sometimes makes it hard to diagnose errors, and makes it hard to compare the environments.
There are several ways to solve this. Either the docker environment could be updated, or the development server could run locally and attach to docker through exposed ports. 

Tasks:
- [x] Build tool updated
- [x] Development environment updated
- [ ] Documentation updated

**Comment by jonandernovella** [comment] 2021-04-20 10:43
Duplicate of #206

**Comment by pontus** [comment] 2021-04-26 08:57
I think this is not a duplicate proper but resolving this should automatically resolve #206.

**Comment by pontus** [comment] 2021-04-26 09:14
I've also finally had a proper look at what `create-react-app` sets up by default, and (probably not surprising) it's webpack based.

From what I can understand, not much has changed from earlier - the considerations are still the same and snowpack will still give be quicker. I'm inclined to continue with (upgraded) snowpack, but am certainly interested if anyone has different opinions.

**Closed as completed** 2021-06-22 09:32 UTC
Labels: enhancement, dependencies, frontend
