### ISSUE TITLE
mandatory fields in certificate form

### ISSUE THREAD

**Issue by HenrikeW** [NBISweden/theherdbook#309] opened 2021-06-09 06:35 UTC
When issuing a certificate, the individual's number, sex and color should be mandatory fields. (notes from the sprint review 25:e maj 21)
--> easy fix in frontend. What about backend?

**Comment by pontus** [comment] 2021-06-09 06:38
Easy to do in the back end as well (but we of course need to keep track of it).

**Comment by jonandernovella** [comment] 2021-06-09 06:39
Duplicate of #287 ?

**Closed as completed** 2021-06-11 13:39 UTC
